name: Main Workflow
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello, world"
      - name: Docker
        uses: docker://ghcr.io/databloom-ai/tpch-docker:main
        with:
          args: /bin/bash -c "./qgen -r 1 -v"
