name: Main Workflow
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello, world"
      - name: Docker
        uses: docker://ubuntu:22.04
        with:
          args: /bin/bas -c "echo Hello world"
